### ISSUE TITLE
Something is not working with the SHELL substitution

### ISSUE THREAD

**Issue by blaggacao** [jlesquembre/kubeprompt#11]
Is this an easy fix?

![image](https://user-images.githubusercontent.com/7548295/94351060-6f37a700-001a-11eb-99a2-e344f57fdf8b.png)
```shell
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/blaggacao/.oh-my-zsh/custom/plugins/nix-shell/scripts/buildShellShim.zsh
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #! /usr/bin/env sh
   2   │
   3   │ if [ "$1" = "--rcfile" ]; then
   4   │   # the rcfile flag indicates that the --command option was used.
   5   │   # This means the shell should stay open after executing. So we remove the last line which contains 'exit'
   6   │   shift
   7   │   tmp="$(cat $1)"
   8   │   echo ${tmp%exit} > $1
   9   │   echo $NIX_EXECUTING_SHELL >> $1
  10   │   bash $1
  11   │ else
  12   │   bash "$@"
  13   │ fi
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by jlesquembre** [comment]
I think that the problem here is the `SHELL` variable value. If I'm not mistaken, you use zsh, but if you execute `SHELL`, bash will be invoked. 
`kubepromt` command starts a sub shell with kubeprompt enabled. The sub shell to launch depends on the value of the environment variable `SHELL`, starting a bash shell if it is not defined.

One possible solution is to set your `SHELL` to zsh, but maybe that breaks something on your setup?

Maybe I could add a new env variable, `KUBEPROMPT_SHELL` or something similar, that takes preference over `SHELL`, but I need to think about it first.

BTW, if you use [direnv](https://direnv.net/), I'm also thinking about making kubeprompt compatible with it, but not sure how, or even if possible

**Comment by blaggacao** [comment]
>Maybe I could add a new env variable, KUBEPROMPT_SHELL or something similar, that takes preference over SHELL, but I need to think about it first.

That sounds like worth a try.

> BTW, if you use direnv, I'm also thinking about making kubeprompt compatible with it, but not sure how, or even if possible

That sounds even a better strategy, since I'm using direnv it handles the heavy lifting for the shell invokation &mdash; which doesn't seem to be trivial.

You could factor out the kubefile mgt logic from the shell invokation logic (`--no-shell`?). Then I would call this simply in my `.envrc` or even `shell.nix` hook. And manually care about how to set the prompt correctly as instructed.

```shell
[...]
export KUBECONFIG=$(kubeprompt --no-shell [...])
export PROMPT="@k8s $(kubeprompt --prompt) [...]"
```

Btw, thanks for this piece of software it's a truely elegant solution to a prominent gitops problem.

**Comment by blaggacao** [comment]
Actually you might (optionally) leave the prompt modification altogether, in proper unix style, to https://github.com/jonmosco/kube-ps1

**Comment by blaggacao** [comment]
I think it was an error on my side and beeing lost with the different shell envs involved with direnv:

- `kubeprompt` works now
- `kubeprompt -f default` does not depend on shell functions and therefore works even when switching shells as oposed to `kube-ps` which works with shell funtions.

Conclusion: nothing to be done.

**Comment by jlesquembre** [comment]
> Actually you might (optionally) leave the prompt modification altogether, in proper unix style, to https://github.com/jonmosco/kube-ps1

Not really, the main reason I started to work on kubeprompt was because kube-ps1 doesn't support the fish shell

It makes sense to add an option like your proposed `--no-shell` (while I like more a name like `--copy-kubeconfig` or something similar) to add support for direnv.

While I still want to add support for direnv, based on you last comment, I think I will not add the `KUBEPROMPT_SHELL` variable
